name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: Check out code
      uses: actions/checkout@v3

    - name: Run linters
      uses: golangci/golangci-lint-action@v3
